# Site settings
title: Michael Letterle's Blog 
description: Phenomenal Cosmic Powers in an itty bitty cubicle 
email: blog@prokrams.com
url: "https://blog.prokrams.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
markdown: kramdown
paginate: 5

plugins:
    - jekyll-paginate
