# Site settings
title: Michael Letterle's Blog 
description: Phenomenal Cosmic Powers in an itty bitty cubicle 
email: blog@prokrams.com
url: "https://blog.prokrams.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty

kramdown:
    input: GFM

highlighter: rouge

exclude:
    - CNAME
    - README.md

plugins:
    - jekyll-paginate

paginate: 5

