# Site settings
title: Michael Letterle's Blog 
description: Phenomenal Cosmic Powers in an itty bitty cubicle 

author:
    name: Michael Letterle
    email: blog@prokrams.com
    twitter: mletterle
    github: mletterle
    stackoverflow: 65235


url: "https://blog.prokrams.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty

kramdown:
    input: GFM

highlighter: rouge

exclude:
    - CNAME
    - README.md

plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-avatar
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

paginate: 5

